---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: openwrt
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: proliant
  virtualRouters:
    - localASN: 65001
      neighbors:
        - peerASN: 64513
          peerAddress: 10.0.1.1/32
      serviceSelector:
         matchExpressions:
            - {key: somekey, operator: NotIn, values: ['never-used-value']}

